version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/solidous/
  AfterInstall:
    - location: script/AfterInstall.sh
#      runas: root
  ApplicationStart:
    - location: script/ApplicationStart.sh
#      runas: root

